### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by mpibpc-mroose** [bewersdorflab/nep-fitting#2]
As Python 2 will get at its end of life end of this year I suggest porting your software to Python 3.

**Comment by barentine** [comment]
This repository should be set for python 3.6, but please open any issues should you find them of course. The largest obstacle for using with python 3 is likely installing PYME, which is possible but not quite yet the default. See [this python-microscopy issue](https://github.com/python-microscopy/python-microscopy/issues/153) for PYME's py3 status at the moment.
