### ISSUE TITLE
Dispatch Python 3 incompatibility

### ISSUE THREAD

**Issue by dpadron08** [bewersdorflab/nep-fitting#4]
nep-fitting relies on [a version](https://conda.anaconda.org/david_baddeley/win-64) of dispatch which is only compatible with Python 2.

**Comment by David-Baddeley** [comment]
Is it an incompatibility with dispatch, or just the fact that we don't currently have a python3 package for it?

**Comment by David-Baddeley** [comment]
There's now an osx build of dispatch for python 3.6, windows and linux builds to follow when I get a chance (alternatively use the conda recipe in python-microscopy/conda-recipes/dispatch to build it yourself)

**Comment by barentine** [comment]
David is correct, dispatch is py3 compatible and there are now py36 packages in his anaconda cloud.
